### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by edalzell** [transformstudios/statamic-events-legacy#6]
- [x] Finalize name \(My vote “Events”\)
- [x] Create icon
- [ ] Review docs
- [ ] Create landing page \(I have addon pages on my new site if we want to start there\)
- [x] Finalize price \(my vote $49\)
- [x] move repo to GH
- [x] screenshots for the marketplace.
- [x] create `DOCUMENTATION.md`
- [x] create README
- [ ] write up on why/how used on client site

‌

**Comment by edalzell** [comment]
Feature image uploaded to this issue. We just need screenshots for the marketplace. Do we use some screenshots from the zaytuna college site? calendar and homepage collection 5?

**Comment by edalzell** [comment]
Zaytuna

**Comment by edalzell** [comment]
Transferred repo issues with: https://github.com/jeffwidman/bitbucket-issue-migration

**Comment by edalzell** [comment]
Launched, moving remaining tasks to individual issues.
